### ISSUE TITLE
Some ZE materials lost on import, all specular colour lost on import

### ISSUE THREAD

**Issue by RJP1992** [Schlechtwetterfront/xsizetools#15]
I have a few models which lose all ZE material attributes upon importing, and I think the loss of specular colour has been around a fairly long time. Is it possible for you to take a look at some example files if you're still active? I have no other details to give other than the imported mesh where material ZE properties are lost has a lot of materials.

**Comment by Schlechtwetterfront** [comment]
If you upload the files somewhere, I can take a look, sure.

Which exporter created those files?

What are the expected values that are lost on import?

**Comment by RJP1992** [comment]
Many thanks! I'll send you the entire folder so you can pick and choose a few examples.

The ones I'm uploading were exported via the blender addon, however it has also happened with models exported with XSIZETOOLS too.

In XSI, it's possibly to define a specular colour for RBG (0 - 1 range) on a material under the specular section. Whatever you set these values to, they are lost upon import (not export as they are read by the game) and all 3 channels read as 1 - pure white.

I have sent a google drive link via your email under your github profile, as the source assets are currently not for public release.

**Comment by Schlechtwetterfront** [comment]
Just FYI: I got your mail, just didn't get around to have a look yet. Hope I'll have some time at the end of the week.

**Comment by RJP1992** [comment]
No rush at all, entirely at your own pace! Thanks for being willing to take a look.

**Comment by Schlechtwetterfront** [comment]
I just pushed some fixes:

* Materials losing ZE props: Some of the material names contained periods, SI replaced those with underscores on import => XSIZETools couldn't find the materials later when trying to apply ZE props.
* Specular color: Seems that was a general problem with how diffuse/ambient/specular values of the shader were set.

Can you check if it fixes your issues? I tested some of the RO_* files and they seemed to be working fine now.
