### ISSUE TITLE
Cloth collisions in a Softimage Model aren't exported correctly

### ISSUE THREAD

**Issue by GT-Anakin** [Schlechtwetterfront/xsizetools#6]
@Schlechtwetterfront If there is a unit with cloth under a model, the collisions are not  #found.

When selecting the collisions they are named _modelname.collisionname_ but that's not an accepted name and by putting just the collision name in the field, ZETools looks for them under Sceneroot instead under the model.

**Comment by Schlechtwetterfront** [comment]
@GT-Anakin, is there any special occasion where that functionality is _necessary_?

**Comment by GT-Anakin** [comment]
@Schlechtwetterfront yes, if you model more then one unit and don't want to have for each unit an own scene. For example i put all swbf3 clones in one scene. That does not work because their bones need to have all the same name, so i need to put them under a model. Now i need to move the dummyroot always to sceneroot and back to it's model

**Comment by Schlechtwetterfront** [comment]
@GT-Anakin I've fixed some naming issues with models in the last release, I haven't tested it ingame though.

**Comment by Schlechtwetterfront** [comment]
@GT-Anakin If you have time, do you mind testing the latest version and checking if cloth from within models now works?

**Comment by GT-Anakin** [comment]
Habe es gerade getestet und es funktioniert wunderbar ;)

Besten Dank
